# Setup
title:        nuMoid's homepage
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       nuMoid
  url:        http://Numoid.Github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown